spring:
  application:
    name: auth-service
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    enabled: true
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/chatdb
    driver-class-name: org.postgresql.Driver
  jpa:
    show_sql: true
    properties:
      hibernate:
security:
  jwt:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
    access_token_expiration: 36000000 # 10 hours
    refresh_token_expiration: 252000000 # 7 days
server:
  port: 0
eureka:
  client:
  service-url:
    defaultZone: http://localhost:8761/eureka/
