spring:
  application:
    name: auth-service
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    enabled: true
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/chatdb
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql:
        format_sql:
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855